<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>GrowGrain</RootNamespace>
    <AssemblyName>SiriusQuality-EnergyBalalnce</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.4.2" />
  </ItemGroup>
</Project>